import { Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useRef, useState, type ReactNode } from "react";
import {
  ArrowRight, ArrowUpRight, Award, BarChart3, BookOpen, BriefcaseBusiness, Camera,
  Check, CheckCircle2, ChevronRight, CirclePause, Clock3, Download, FileText,
  Github, GraduationCap, Headphones, LayoutDashboard, LockKeyhole, Menu, MessageSquare,
  Mic, MicOff, MonitorUp, MoreHorizontal, Network, NotebookPen, Pause, Play, Plus,
  Radio, RefreshCw, Route, Send, ShieldCheck, Sparkles, Target, Upload, UserRound,
  Video, VideoOff, Volume2, WandSparkles, X, Zap,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Message, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputBody, PromptInputFooter, PromptInputSubmit, PromptInputTextarea, PromptInputTools } from "@/components/ai-elements/prompt-input";
import alexImage from "@/assets/interviewer-alex.jpg";
import candidateImage from "@/assets/candidate-arjun.jpg";
import { cn } from "@/lib/utils";

type EchoMode = "idle" | "listening" | "thinking" | "speaking";

const violetButton = "rounded-none bg-brand px-5 font-semibold text-white shadow-[4px_4px_0_#16121d] hover:bg-brand/90 hover:translate-x-[1px] hover:translate-y-[1px] hover:shadow-[2px_2px_0_#16121d]";
const outlineButton = "rounded-none border-foreground/30 bg-transparent shadow-none hover:bg-foreground hover:text-background";
const panel = "border border-foreground/15 bg-card shadow-[6px_6px_0_rgba(25,18,35,.09)]";

function Logo({ dark = false }: { dark?: boolean }) {
  return <Link to="/" className={cn("flex items-center gap-2 text-lg font-bold tracking-tight", dark && "text-white")}>
    <span className="grid size-8 place-items-center bg-brand text-white shadow-[3px_3px_0_#f2dc47]"><Radio className="size-4" /></span>
    EchoSphere
  </Link>;
}

function Header({ dark = false, compact = false }: { dark?: boolean; compact?: boolean }) {
  return <header className={cn("relative z-40 flex h-16 items-center justify-between border-b px-5 md:px-9", dark ? "border-white/10 bg-[#17131c] text-white" : "border-foreground/15 bg-background", compact && "h-14")}>
    <Logo dark={dark} />
    <div className="flex items-center gap-3">
      {!compact && <><span className={cn("hidden items-center gap-2 text-xs md:flex", dark ? "text-white/55" : "text-muted-foreground")}><span className="size-2 rounded-full bg-success" /> AI ONLINE</span><Link to="/dashboard"><Button variant="ghost" size="sm">Dashboard</Button></Link></>}
      <button className={cn("grid size-9 place-items-center border text-sm font-semibold", dark ? "border-white/20 bg-white/10" : "border-foreground/20 bg-white")}>AS</button>
    </div>
  </header>;
}

function Eyebrow({ children, dark = false }: { children: ReactNode; dark?: boolean }) {
  return <div className={cn("mb-4 flex items-center gap-2 font-mono text-[11px] font-medium uppercase tracking-[.18em]", dark ? "text-[#bcb0c8]" : "text-brand")}><span className="h-px w-6 bg-current" />{children}</div>;
}

function EchoOrb({ mode = "idle", onClick, small = false }: { mode?: EchoMode; onClick?: () => void; small?: boolean }) {
  return <button onClick={onClick} aria-label="Activate Echo voice assistant" className={cn("echo-pulse relative grid rounded-full bg-brand text-white transition-transform hover:scale-105", small ? "size-11" : "size-16")}>
    <span className="absolute inset-[5px] rounded-full border border-white/30" />
    <span className="flex h-full items-center justify-center gap-[3px]">
      {[.5, .85, 1, .65, .4].map((height, i) => <i key={i} className={cn("w-[2px] rounded-full bg-white", mode !== "idle" && "echo-wave")} style={{ height: `${height * (small ? 16 : 23)}px`, animationDelay: `${i * 90}ms` }} />)}
    </span>
  </button>;
}

function EchoAssistant({ dark = false, hint = "What would you like to work on?" }: { dark?: boolean; hint?: string }) {
  const [open, setOpen] = useState(false);
  const [mode, setMode] = useState<EchoMode>("idle");
  const [answer, setAnswer] = useState("");
  function activate() {
    setOpen(true); setMode("listening"); setAnswer("");
    window.setTimeout(() => setMode("thinking"), 1300);
    window.setTimeout(() => { setMode("speaking"); setAnswer("Your Product Thinking score has the most room to grow. I can start a focused 10-minute practice session."); }, 2400);
    window.setTimeout(() => setMode("idle"), 5200);
  }
  return <div className="fixed bottom-5 right-5 z-50 flex items-end gap-3">
    {open && <div className={cn("w-[min(360px,calc(100vw-90px))] border p-4 shadow-2xl", dark ? "border-white/15 bg-[#211b27] text-white" : "border-foreground/20 bg-white")}>
      <div className="mb-3 flex items-start justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-brand">Echo assistant</p><p className="mt-1 text-sm font-semibold">{mode === "listening" ? "Listening…" : mode === "thinking" ? "Thinking…" : mode === "speaking" ? "Speaking" : hint}</p></div><button aria-label="Close Echo Assistant" onClick={() => setOpen(false)}><X className="size-4 opacity-60" /></button></div>
      {answer && <p className={cn("border-l-2 border-highlight pl-3 text-sm leading-6", dark ? "text-white/70" : "text-muted-foreground")}>{answer}</p>}
      <div className="mt-4 flex flex-wrap gap-2">{["Start interview", "Review report", "Practice weak skill"].map(x => <button onClick={activate} key={x} className={cn("border px-2.5 py-1.5 text-[11px]", dark ? "border-white/15 hover:bg-white/10" : "border-foreground/15 hover:bg-muted")}>{x}</button>)}</div>
    </div>}
    <div className="flex flex-col items-center gap-1.5"><EchoOrb small onClick={open ? activate : () => setOpen(true)} mode={mode} /><span className={cn("font-mono text-[9px] uppercase tracking-wider", dark ? "text-white/65" : "text-muted-foreground")}>Hey Echo</span></div>
  </div>;
}

const personas = [
  ["Alex", "Technical Interviewer", "A"], ["Maya", "Product Manager", "M"], ["Daniel", "Hiring Manager", "D"], ["Sophia", "Behavioral Interviewer", "S"], ["Jordan", "Customer / Role-play", "J"],
];

export function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f4fb] text-foreground">
    <Header />
    <section className="relative grid min-h-[680px] border-b border-foreground/15 lg:grid-cols-[1.08fr_.92fr]">
      <div className="relative flex flex-col justify-center px-6 py-20 md:px-12 lg:px-[7vw]">
        <div className="absolute left-[3vw] top-14 h-28 w-px bg-foreground/10" /><Eyebrow>Adaptive intelligence, in conversation</Eyebrow>
        <h1 className="max-w-3xl text-[clamp(3.2rem,7vw,7.6rem)] font-semibold leading-[.87] tracking-[-.07em]">Every answer<br /><span className="text-brand">shapes the</span><br />next question.</h1>
        <p className="mt-8 max-w-xl text-base leading-7 text-muted-foreground md:text-lg">Voice-first interviews led by a coordinated AI panel. Adaptive questioning, real-time context, and evidence-backed feedback—built around how you think.</p>
        <div className="mt-9 flex flex-wrap gap-4"><Link to="/portal"><Button size="lg" className={violetButton}>Are you a Candidate? <ArrowRight /></Button></Link><Button size="lg" variant="outline" className={outlineButton}>Are you an Organization? <ArrowUpRight /></Button></div>
        <div className="mt-12 flex items-center gap-5 border-t border-foreground/15 pt-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><ShieldCheck className="size-4 text-brand" /> Encrypted voice & identity</span><span className="flex items-center gap-2"><Zap className="size-4 text-brand" /> Adaptive in real time</span></div>
      </div>
      <div className="relative min-h-[560px] overflow-hidden bg-brand p-6 text-white md:p-10">
        <div className="absolute -right-20 top-10 size-72 rounded-full border border-white/15" /><div className="absolute -right-2 top-28 size-48 rounded-full border border-highlight/40" />
        <div className="relative mx-auto flex h-full max-w-xl flex-col justify-center">
          <div className="mb-4 flex items-center justify-between font-mono text-[10px] uppercase tracking-widest text-white/65"><span>Live adaptive panel</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-highlight" /> Listening</span></div>
          <div className="border border-white/20 bg-[#20192a]/90 p-5 shadow-[10px_10px_0_#f2dc47] md:p-7">
            <div className="flex items-center gap-4 border-b border-white/10 pb-5"><EchoOrb mode="speaking" /><div><p className="font-mono text-[10px] uppercase tracking-widest text-[#cbbddd]">Alex · Technical Interviewer</p><h2 className="mt-1 text-xl font-medium">“Let’s follow that decision.”</h2></div></div>
            <div className="py-8"><p className="font-mono text-[10px] uppercase tracking-widest text-highlight">System design · Follow-up</p><p className="mt-3 text-2xl leading-tight md:text-3xl">How would your architecture change if traffic grew tenfold overnight?</p></div>
            <div className="grid grid-cols-5 gap-2">{personas.map(([name, role, letter], i) => <div key={name} className={cn("border p-2.5", i === 0 ? "border-highlight bg-highlight text-highlight-foreground" : "border-white/15 bg-white/5")}><span className="grid size-7 place-items-center border border-current font-mono text-xs">{letter}</span><p className="mt-2 text-xs font-semibold">{name}</p><p className="hidden text-[9px] opacity-60 md:block">{role}</p></div>)}</div>
          </div>
        </div>
      </div>
    </section>
    <section className="grid border-b border-foreground/15 md:grid-cols-3">{[
      ["01", "Adaptive voice interviews", "Questions evolve with every answer—not from a fixed script.", Mic], ["02", "A coordinated AI panel", "Distinct perspectives hand off in one continuous conversation.", Headphones], ["03", "Evidence-backed feedback", "Every score links to transcript evidence and practical next steps.", BarChart3]
    ].map(([n,t,d,I]: any) => <article key={n} className="border-b border-foreground/15 p-8 last:border-0 md:border-b-0 md:border-r md:last:border-r-0"><div className="flex justify-between"><span className="font-mono text-xs text-brand">{n}</span><I className="size-5" /></div><h3 className="mt-12 text-2xl font-semibold">{t}</h3><p className="mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{d}</p></article>)}</section>
    <section className="bg-[#1b1720] px-6 py-20 text-white md:px-12"><div className="mx-auto max-w-6xl"><Eyebrow dark>The panel</Eyebrow><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="max-w-2xl text-4xl font-semibold tracking-tight md:text-6xl">Five perspectives.<br /><span className="text-highlight">One continuous interview.</span></h2><p className="max-w-sm text-sm leading-6 text-white/55">The right interviewer steps forward at the right moment, while shared context keeps every handoff seamless.</p></div><div className="mt-12 grid gap-px bg-white/10 sm:grid-cols-2 lg:grid-cols-5">{personas.map(([n,r,l],i)=><div key={n} className="bg-[#1b1720] p-5"><span className={cn("grid size-11 place-items-center border font-mono",i===0?"border-highlight bg-highlight text-black":"border-white/20")}>{l}</span><h3 className="mt-8 text-lg font-semibold">{n}</h3><p className="mt-1 text-xs text-white/50">{r}</p></div>)}</div></div></section>
  </main>;
}

export function PortalPage() {
  const navigate = useNavigate();
  return <main className="min-h-screen bg-[#f5f1f8]"><Header /><div className="grid min-h-[calc(100vh-64px)] lg:grid-cols-[.9fr_1.1fr]">
    <section className="flex items-center px-6 py-16 md:px-[9vw]"><div className="w-full max-w-lg"><Eyebrow>Candidate access</Eyebrow><h1 className="text-5xl font-semibold tracking-[-.05em] md:text-7xl">Enter your<br /><span className="text-brand">interview space.</span></h1><p className="mt-5 text-muted-foreground">Practice AI voice interviews with a panel that adapts to you.</p><form onSubmit={e=>{e.preventDefault();navigate({to:"/dashboard"})}} className="mt-10"><label className="font-mono text-[10px] uppercase tracking-widest">Work or personal email</label><input type="email" defaultValue="arjun.sharma@example.com" required className="mt-2 h-13 w-full border border-foreground/25 bg-white px-4 outline-none focus:border-brand"/><Button className={cn(violetButton,"mt-4 h-12 w-full")}>Continue to Candidate Dashboard <ArrowRight /></Button></form><div className="mt-9 grid gap-3 sm:grid-cols-2"><Link to="/dashboard" className="border border-foreground/15 bg-white p-4 hover:border-brand"><p className="font-semibold">Quick launch</p><p className="mt-1 text-xs text-muted-foreground">Enter Demo Candidate Workspace</p></Link><div className="border border-foreground/15 bg-white p-4"><p className="font-semibold">Assessment</p><button onClick={()=>navigate({to:"/dashboard"})} className="mt-1 text-xs text-brand underline">Enter Access Code</button></div></div><p className="mt-8 flex items-center gap-2 text-xs text-muted-foreground"><LockKeyhole className="size-4 text-success" /> End-to-End Voice & Identity Encryption</p></div></section>
    <section className="relative hidden overflow-hidden bg-brand p-14 text-white lg:flex lg:items-center"><div className="absolute -right-32 -top-32 size-[550px] rounded-full border border-white/10"/><div className="relative max-w-lg"><EchoOrb mode="speaking"/><p className="mt-12 font-mono text-xs uppercase tracking-[.2em] text-highlight">Echo is ready</p><h2 className="mt-4 text-4xl font-semibold leading-tight">A quiet, intelligent space to sharpen how you answer.</h2><div className="mt-12 border-l border-white/25 pl-6"><p className="text-lg">“What would you like to work on?”</p><div className="mt-5 flex gap-2">{["System design","Behavioral","Product thinking"].map(x=><span key={x} className="border border-white/20 px-3 py-2 text-xs">{x}</span>)}</div></div></div></section>
  </div><EchoAssistant /></main>;
}

const competencies = [["Technical",84],["Problem Solving",78],["Communication",86],["Product Thinking",61],["Leadership",75],["Behavioral",82],["Adaptability",79]] as const;
const sessions = [
  {state:"IN PROGRESS",company:"Google",role:"Senior Software Engineer",date:"Today",score:"—",action:"Resume"},
  {state:"COMPLETED",company:"Amazon",role:"Backend Engineer",date:"May 18, 2025",score:"82",action:"View Report"},
  {state:"SCHEDULED",company:"Microsoft",role:"Staff Software Engineer",date:"May 28, 2025",score:"—",action:"Details"},
];
export function DashboardPage() {
  return <main className="min-h-screen bg-[#f5f1f8]"><Header/><div className="mx-auto max-w-7xl px-5 py-10 md:px-10">
    <div className="flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><div><Eyebrow>Candidate workspace</Eyebrow><h1 className="text-4xl font-semibold tracking-[-.04em] md:text-6xl">Welcome back, <span className="text-brand">Arjun.</span></h1><p className="mt-2 text-muted-foreground">arjun.sharma@example.com</p></div><div className="flex flex-wrap gap-2"><Link to="/setup"><Button className={violetButton}><Plus/> Start New Mock Interview</Button></Link>{[[UserRound,"View Profile","/profile"],[FileText,"Reports","/report"],[Route,"Roadmap","/report"]].map(([I,t,to]:any)=><Link key={t} to={to}><Button variant="outline" className={outlineButton}><I/>{t}</Button></Link>)}</div></div>
    <section className="mt-10 grid border border-foreground/15 bg-white sm:grid-cols-2 lg:grid-cols-4">{[[Clock3,"Upcoming","1"],[CheckCircle2,"Completed","7"],[Award,"Average score","78"],[UserRound,"Profile","88%"]].map(([I,l,v]:any)=><div key={l} className="border-b border-foreground/15 p-5 last:border-0 sm:border-r lg:border-b-0"><div className="flex justify-between text-muted-foreground"><span className="font-mono text-[10px] uppercase tracking-widest">{l}</span><I className="size-4"/></div><p className="mt-8 text-4xl font-semibold">{v}</p></div>)}</section>
    <div className="mt-8 grid gap-8 lg:grid-cols-[1.4fr_.6fr]"><section><div className="mb-4 flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-brand">Interview history</p><h2 className="mt-1 text-2xl font-semibold">Your sessions</h2></div><span className="text-xs text-muted-foreground">3 recent</span></div><div className="border-t border-foreground/20">{sessions.map((s,i)=><article key={s.company} className="grid items-center gap-4 border-b border-foreground/15 bg-white p-5 md:grid-cols-[36px_1fr_120px_80px_120px]"><span className="font-mono text-xs text-muted-foreground">0{i+1}</span><div><span className={cn("font-mono text-[9px] tracking-widest",s.state==="COMPLETED"?"text-success":s.state==="IN PROGRESS"?"text-brand":"text-muted-foreground")}>● {s.state}</span><h3 className="mt-1 font-semibold">{s.company} · {s.role}</h3></div><p className="text-xs text-muted-foreground">{s.date}</p><p className="text-2xl font-semibold">{s.score}</p><Link to={s.action==="Resume"?"/interview/demo":s.action==="View Report"?"/report":"/setup"}><Button variant="outline" size="sm" className={outlineButton}>{s.action}</Button></Link></article>)}</div></section>
      <aside className="space-y-5"><div className={cn(panel,"p-5")}><div className="flex justify-between"><h2 className="font-semibold">Profile completion</h2><span className="font-mono text-sm text-brand">88%</span></div><div className="mt-4 h-2 bg-muted"><div className="h-full w-[88%] bg-highlight"/></div><Link to="/profile" className="mt-3 inline-flex items-center text-xs text-brand">Complete profile <ChevronRight className="size-3"/></Link></div><div className={cn(panel,"p-5")}><h2 className="font-semibold">Competency overview</h2><div className="mt-5 space-y-3">{competencies.map(([c,v])=><div key={c}><div className="mb-1 flex justify-between text-xs"><span>{c}</span><b>{v}</b></div><div className="h-1.5 bg-muted"><div className="h-full bg-brand" style={{width:`${v}%`}}/></div></div>)}</div></div><div className="bg-[#201b26] p-5 text-white"><div className="flex justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-highlight">Roadmap progress</p><p className="mt-2 text-2xl font-semibold">6 of 10</p></div><Route className="text-highlight"/></div><p className="mt-4 text-xs text-white/55">Next: connect technical decisions to customer impact.</p></div></aside></div>
  </div><EchoAssistant/></main>;
}

const setupSteps = ["Target company","Target role","Domain & focus","AI proposal","Confirm"];
export function SetupPage() {
  const navigate=useNavigate(); const [step,setStep]=useState(0); const [company,setCompany]=useState("Google"); const [role,setRole]=useState("Senior Software Engineer"); const [domain,setDomain]=useState("Data Engineering"); const [difficulty,setDifficulty]=useState("Hard");
  const companies=["Google","Microsoft","Amazon","Apple","Meta","Netflix","Uber"]; const roles=["Software Engineer","Senior Software Engineer","Staff Software Engineer","Frontend Engineer","Backend Engineer","Full Stack Engineer","Data Engineer"];
  return <main className="min-h-screen bg-[#f5f1f8]"><Header/><div className="border-b border-foreground/15 bg-white px-5 py-6"><div className="mx-auto flex max-w-6xl gap-1 overflow-x-auto">{setupSteps.map((s,i)=><button onClick={()=>setStep(i)} key={s} className={cn("flex min-w-40 flex-1 items-center gap-3 border-b-2 pb-3 text-left",i===step?"border-brand text-foreground":i<step?"border-success text-muted-foreground":"border-foreground/10 text-muted-foreground")}><span className={cn("grid size-7 shrink-0 place-items-center border font-mono text-xs",i===step&&"border-brand bg-brand text-white",i<step&&"border-success bg-success text-white")}>{i<step?<Check className="size-3"/>:i+1}</span><span className="text-xs font-semibold">{s}</span></button>)}</div></div>
    <div className="mx-auto grid max-w-6xl gap-10 px-5 py-12 lg:grid-cols-[1fr_310px]"><section><Eyebrow>Interview configuration · Step {step+1} of 5</Eyebrow>{step===0&&<ChoiceStep title="Where do you want to interview?" subtitle="Choose a target company so Echo can tune the interview context." items={companies} value={company} setValue={setCompany}/>} {step===1&&<ChoiceStep title="Which role are you targeting?" subtitle="This determines the expected scope and interview panel." items={roles} value={role} setValue={setRole}/>} {step===2&&<ChoiceStep title="Choose your domain & competency focus." subtitle="Select the course or domain that should guide the interview." items={["Data Engineering","Backend Systems","Frontend Architecture","Machine Learning","Product Engineering"]} value={domain} setValue={setDomain}/>} {step===3&&<Proposal difficulty={difficulty} setDifficulty={setDifficulty}/>} {step===4&&<ConfirmSetup company={company} role={role} domain={domain} difficulty={difficulty}/>}<div className="mt-10 flex justify-between"><Button disabled={step===0} onClick={()=>setStep(x=>x-1)} variant="outline" className={outlineButton}>Back</Button>{step<4?<Button onClick={()=>setStep(x=>x+1)} className={violetButton}>Continue <ArrowRight/></Button>:<Button onClick={()=>navigate({to:"/profile"})} className={violetButton}>Proceed to Candidate Information <ArrowRight/></Button>}</div></section>
      <aside><div className="sticky top-24 bg-[#201b26] p-6 text-white shadow-[7px_7px_0_#f2dc47]"><EchoOrb small mode="speaking"/><p className="mt-6 font-mono text-[10px] uppercase tracking-widest text-highlight">Echo insight</p><p className="mt-3 text-lg leading-7">{step<2?"I’ll use this to calibrate scope, seniority, and likely interview patterns.":step===2?"Your focus will shape both the questions and how evidence is scored.":"I’ve inferred a three-person panel based on the role. Your interview will emphasize system design and technical depth."}</p><div className="mt-6 border-t border-white/15 pt-4 text-xs text-white/50">Say “Hey Echo, configure this interview for me.”</div></div></aside></div><EchoAssistant/></main>;
}

function ChoiceStep({title,subtitle,items,value,setValue}:{title:string;subtitle:string;items:string[];value:string;setValue:(v:string)=>void}) { return <><h1 className="max-w-3xl text-4xl font-semibold tracking-tight md:text-6xl">{title}</h1><p className="mt-4 text-muted-foreground">{subtitle}</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{items.map((x,i)=><button onClick={()=>setValue(x)} key={x} className={cn("flex min-h-20 items-center justify-between border p-5 text-left font-semibold transition",value===x?"border-brand bg-brand text-white shadow-[5px_5px_0_#f2dc47]":"border-foreground/15 bg-white hover:border-brand")}><span><i className="mr-3 font-mono text-xs not-italic opacity-50">0{i+1}</i>{x}</span>{value===x&&<Check/>}</button>)}</div></> }
function Proposal({difficulty,setDifficulty}:{difficulty:string;setDifficulty:(v:string)=>void}) { const weights=[["Technical",35],["System Design",30],["Problem Solving",20],["Behavioral",10],["Communication",5]] as const; return <><h1 className="text-4xl font-semibold tracking-tight md:text-6xl">Your adaptive<br/><span className="text-brand">AI proposal.</span></h1><div className="mt-9 grid gap-5 md:grid-cols-2"><div className={cn(panel,"p-6")}><h3 className="font-semibold">Competency weighting</h3><div className="mt-5 space-y-4">{weights.map(([n,v])=><div key={n}><div className="flex justify-between text-xs"><span>{n}</span><b>{v}%</b></div><div className="mt-1 h-2 bg-muted"><div className="h-full bg-brand" style={{width:`${v}%`}}/></div></div>)}</div></div><div className={cn(panel,"p-6")}><h3 className="font-semibold">Inferred interview panel</h3><div className="mt-5 space-y-3">{[["A","Technical Interviewer"],["M","Domain Expert"],["D","Hiring Manager"]].map(([a,r])=><div key={a} className="flex items-center gap-3 border-b border-foreground/10 pb-3"><span className="grid size-9 place-items-center bg-foreground text-white">{a}</span><span className="text-sm font-medium">{r}</span></div>)}</div></div><div className={cn(panel,"p-6 md:col-span-2")}><h3 className="font-semibold">Course focus areas</h3><div className="mt-4 flex flex-wrap gap-2">{["Spark/Kafka Streaming","Data Warehousing","ETL Pipelines","Data Quality & Schema Design"].map(x=><span key={x} className="border border-foreground/15 bg-muted px-3 py-2 text-xs">{x}</span>)}</div><h3 className="mt-7 font-semibold">Target difficulty</h3><div className="mt-3 grid grid-cols-4 gap-2">{["Easy","Medium","Hard","Expert"].map(x=><button key={x} onClick={()=>setDifficulty(x)} className={cn("border p-3 text-xs font-semibold",difficulty===x?"border-brand bg-brand text-white":"border-foreground/15")}>{x}</button>)}</div></div></div></> }
function ConfirmSetup({company,role,domain,difficulty}:{company:string;role:string;domain:string;difficulty:string}) { return <><h1 className="text-4xl font-semibold tracking-tight md:text-6xl">Confirm mock<br/><span className="text-brand">interview setup.</span></h1><div className={cn(panel,"mt-9 divide-y divide-foreground/10")}>{[[BriefcaseBusiness,"Company",company],[UserRound,"Role",role],[Target,"Domain",domain],[Zap,"Difficulty",difficulty],[Headphones,"Interview mode","Assessment / Mock Interview"]].map(([I,l,v]:any)=><div key={l} className="grid grid-cols-[40px_150px_1fr] items-center p-5"><I className="size-5 text-brand"/><span className="font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{l}</span><b>{v}</b></div>)}</div></> }

export function ProfilePage() {
  const navigate=useNavigate(); const [file,setFile]=useState("");
  return <main className="min-h-screen bg-[#f5f1f8]"><Header/><div className="mx-auto max-w-6xl px-5 py-12"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><Eyebrow>Context builder</Eyebrow><h1 className="text-4xl font-semibold tracking-tight md:text-6xl">Personal Information Portal</h1><p className="mt-3 max-w-2xl text-muted-foreground">Provide your resume, project repository, education and certifications to personalize the AI mock interviewer.</p></div><div className="w-56"><p className="flex justify-between font-mono text-[10px] uppercase"><span>Context complete</span><b>72%</b></p><div className="mt-2 h-2 bg-white"><div className="h-full w-[72%] bg-brand"/></div></div></div>
    <form onSubmit={e=>{e.preventDefault();navigate({to:"/system-check"})}} className="mt-10 grid gap-6 lg:grid-cols-[1fr_1fr]">
      <FormSection number="A" title="Candidate resume" icon={<FileText/>}><label className="grid min-h-40 cursor-pointer place-items-center border border-dashed border-foreground/30 bg-muted/50 text-center hover:border-brand"><input type="file" accept=".pdf,.doc,.docx" className="hidden" onChange={e=>setFile(e.target.files?.[0]?.name||"")}/><div><Upload className="mx-auto mb-3 text-brand"/><b>{file||"Drop your resume or browse"}</b><p className="mt-1 text-xs text-muted-foreground">PDF, DOC, DOCX · Maximum 10MB</p></div></label></FormSection>
      <FormSection number="B" title="Best project GitHub link" icon={<Github/>}><label className="text-xs font-semibold">Repository URL<input type="url" defaultValue="https://github.com/arjunsharma/distributed-cache" className="mt-2 h-11 w-full border border-foreground/20 px-3 outline-none focus:border-brand"/></label><p className="mt-3 text-xs leading-5 text-muted-foreground">The interviewer will evaluate code structure and architecture from this project.</p></FormSection>
      <FormSection number="C" title="Educational details" icon={<GraduationCap/>}><div className="grid gap-4 sm:grid-cols-2">{[["Institution / College / University","Indian Institute of Technology"],["Degree","B.Tech"],["Department / Branch","Computer Science"],["Graduation Year","2021"]].map(([l,v])=><label key={l} className="text-xs font-semibold">{l}<input defaultValue={v} className="mt-2 h-11 w-full border border-foreground/20 px-3 outline-none focus:border-brand"/></label>)}</div></FormSection>
      <FormSection number="D" title="Certifications" icon={<Award/>}><div className="grid gap-3 sm:grid-cols-2">{[["Certification Name","AWS Solutions Architect"],["Issuing Organization","Amazon Web Services"],["Year / Issue Date","2024"],["Credential URL","https://credential.example"]].map(([l,v])=><label key={l} className="text-xs font-semibold">{l}<input defaultValue={v} className="mt-2 h-11 w-full border border-foreground/20 px-3 outline-none focus:border-brand"/></label>)}</div><Button type="button" variant="outline" size="sm" className={cn(outlineButton,"mt-4")}><Plus/> Add certification</Button></FormSection>
      <div className="flex items-center justify-between border-t border-foreground/15 pt-6 lg:col-span-2"><p className="flex items-center gap-2 text-xs text-muted-foreground"><Sparkles className="size-4 text-brand"/> EchoSphere is building your interview context…</p><Button className={violetButton}>Save & Continue to System Check <ArrowRight/></Button></div>
    </form></div><EchoAssistant/></main>;
}
function FormSection({number,title,icon,children}:{number:string;title:string;icon:ReactNode;children:ReactNode}) { return <section className={cn(panel,"p-6")}><div className="mb-6 flex items-center justify-between"><div className="flex items-center gap-3"><span className="font-mono text-xs text-brand">{number}</span><h2 className="text-xl font-semibold">{title}</h2></div><span className="text-brand">{icon}</span></div>{children}</section> }

type CheckStatus="PASS"|"NOT ACTIVE"|"FAIL"|"CHECKING";
export function SystemCheckPage() {
  const navigate=useNavigate(); const [statuses,setStatuses]=useState<CheckStatus[]>(["PASS","NOT ACTIVE","NOT ACTIVE","PASS"]); const [camera,setCamera]=useState(false); const video=useRef<HTMLVideoElement>(null);
  async function enableCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(video.current)video.current.srcObject=s;setCamera(true);setStatuses(["PASS","PASS",statuses[2],"PASS"])}catch{setStatuses(["FAIL","FAIL",statuses[2],"PASS"])}}
  function screen(){setStatuses([statuses[0],statuses[1],"CHECKING",statuses[3]]);navigator.mediaDevices?.getDisplayMedia?.({video:true}).then(()=>setStatuses([statuses[0],statuses[1],"PASS",statuses[3]])).catch(()=>setStatuses([statuses[0],statuses[1],"NOT ACTIVE",statuses[3]]))}
  const ready=statuses.every(x=>x==="PASS");
  return <main className="min-h-screen bg-[#f5f1f8] text-foreground"><Header/><div className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><Eyebrow>Pre-flight check</Eyebrow><h1 className="text-4xl font-semibold tracking-tight md:text-6xl">System environment check</h1></div><div className={cn("border px-5 py-3 font-mono text-sm",ready?"border-success text-success":"border-highlight bg-highlight/10 text-highlight-foreground")}><span className="mr-3 inline-block size-2 rounded-full bg-current"/>{ready?"READY":"ACTION REQUIRED"}</div></div>
    <div className="mt-9 grid gap-4 md:grid-cols-2"><CheckCard icon={<Camera/>} n="01" title="Camera Access & Video Preview" status={statuses[0]}><div className="relative aspect-video overflow-hidden bg-muted">{camera?<video ref={video} autoPlay muted className="size-full object-cover"/>:<div className="grid size-full place-items-center"><Button onClick={enableCamera} className={violetButton}><Camera/> Enable Camera & Microphone</Button></div>}</div></CheckCard>
    <CheckCard icon={<Mic/>} n="02" title="Microphone Access & Input Level" status={statuses[1]}><div className="flex h-28 items-center gap-1 bg-muted px-8">{Array.from({length:28},(_,i)=><i key={i} className="w-1 bg-brand" style={{height:camera?`${18+(i*13)%62}%`:"8%"}}/>)}</div></CheckCard>
    <CheckCard icon={<MonitorUp/>} n="03" title="Screen Sharing Verification" status={statuses[2]}><div className="flex h-28 items-center justify-between bg-muted px-5"><span className="text-sm text-muted-foreground">{statuses[2]==="PASS"?"Screen sharing verified":"Screen Sharing Not Started"}</span><Button onClick={screen} variant="outline" className={outlineButton}>Share Screen Now</Button></div></CheckCard>
    <CheckCard icon={<Network/>} n="04" title="Real Network & Backend Health" status={statuses[3]}><div className="grid h-28 grid-cols-2 place-items-center bg-muted"><div><p className="text-xs text-muted-foreground">Backend Reachable</p><b className="text-success">Yes</b></div><div><p className="text-xs text-muted-foreground">Latency</p><b>42 ms</b></div></div><button className="mt-3 flex items-center gap-2 text-xs text-brand"><RefreshCw className="size-3"/> Re-check Connectivity</button></CheckCard></div>
    <div className="mt-8 flex justify-end"><Button disabled={!ready} onClick={()=>navigate({to:"/video-test"})} className={cn(violetButton,"disabled:shadow-none")}>Continue to Sample Video <ArrowRight/></Button></div></div></main>;
}
function CheckCard({n,title,status,icon,children}:{n:string;title:string;status:CheckStatus;icon:ReactNode;children:ReactNode}) { return <section className={cn(panel,"p-5")}><div className="mb-5 flex items-center justify-between"><div className="flex items-center gap-3 text-sm font-semibold"><span className="font-mono text-[10px] text-muted-foreground">{n}</span><span className="text-brand">{icon}</span>{title}</div><Status status={status}/></div>{children}</section> }
function Status({status}:{status:CheckStatus}) { return <span className={cn("border px-2 py-1 font-mono text-[9px]",status==="PASS"?"border-success/40 text-success":status==="FAIL"?"border-red-400 text-red-400":status==="CHECKING"?"border-info text-info":"border-foreground/20 text-muted-foreground")}>{status}</span> }

export function VideoTestPage() {
  const navigate=useNavigate(); const [recording,setRecording]=useState(false); const [done,setDone]=useState(false); const [seconds,setSeconds]=useState(0);
  useEffect(()=>{if(!recording)return;const id=window.setInterval(()=>setSeconds(s=>{if(s>=29){setRecording(false);setDone(true);return 30}return s+1}),1000);return()=>clearInterval(id)},[recording]);
  return <main className="min-h-screen bg-[#17131c] text-white"><Header dark/><div className="mx-auto max-w-6xl px-5 py-10"><Eyebrow dark>Voice & presence calibration</Eyebrow><div className="grid gap-9 lg:grid-cols-[350px_1fr]"><section><h1 className="text-4xl font-semibold tracking-tight">Sample Video Question</h1><div className="mt-8 border-l-2 border-highlight pl-5"><p className="font-mono text-[10px] uppercase tracking-widest text-highlight">Your question</p><blockquote className="mt-3 text-3xl leading-tight">“What is your favourite colour?”</blockquote></div><div className="mt-8 space-y-3 text-sm text-white/55"><p className="flex gap-3"><span className="font-mono text-highlight">01</span> Answer naturally for 10–30 seconds.</p><p className="flex gap-3"><span className="font-mono text-highlight">02</span> Speak clearly in your normal tone.</p></div></section><section><div className="relative aspect-video overflow-hidden border border-white/15 bg-black"><img src={candidateImage} alt="Candidate video preview" width={640} height={640} className="size-full object-cover"/>{recording&&<><span className="absolute left-4 top-4 flex items-center gap-2 bg-red-500 px-3 py-1.5 font-mono text-[10px]"><i className="size-2 rounded-full bg-white"/> RECORDING</span><div className="absolute inset-x-0 bottom-0 flex h-16 items-center justify-center gap-1 bg-gradient-to-t from-black/80">{Array.from({length:44},(_,i)=><i key={i} className="echo-wave w-1 bg-highlight" style={{height:`${10+(i*17)%35}px`,animationDelay:`${i*25}ms`}}/>)}</div></>}</div><div className="mt-4 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-white/45">Live Camera Recorder</p><p className="mt-1 text-2xl font-semibold">{seconds}s <span className="text-white/35">/ 30s</span></p></div><div className="flex gap-3">{!done?<Button onClick={()=>{setRecording(!recording);setSeconds(0)}} className={recording?"rounded-none bg-red-500":"rounded-none bg-white text-black hover:bg-highlight"}>{recording?<><Pause/> Stop Recording</>:<><Radio/> Start Recording</>}</Button>:<Button onClick={()=>navigate({to:"/analysis"})} className={violetButton}>Submit for AI Analysis <Sparkles/></Button>}</div></div>{done&&<div className="mt-5 border border-success/30 bg-success/5 p-4 text-sm text-success"><CheckCircle2 className="mr-2 inline size-4"/> Recording complete · {seconds} seconds · Ready for review</div>}</section></div></div></main>;
}

export function AnalysisPage() {
  const navigate=useNavigate(); const verifications=[[Camera,"Camera & Video Quality","HD video, stable exposure, face clearly visible."],[Mic,"Microphone & Audio Level","Clear voice signal with low background noise."],[MonitorUp,"Screen Sharing Verification","Screen access verified and available."],[ShieldCheck,"Sample Recording Integrity","30-second recording passed integrity analysis."]];
  return <main className="min-h-screen bg-[#f5f1f8]"><Header/><div className="mx-auto max-w-5xl px-5 py-12"><div className="text-center"><Eyebrow>Automated evaluation</Eyebrow><h1 className="text-4xl font-semibold tracking-tight md:text-6xl">Candidate Analysis Portal</h1><div className="mx-auto mt-8 grid size-32 place-items-center rounded-full border-2 border-success bg-white shadow-[8px_8px_0_#bff3cf]"><div><Check className="mx-auto size-8 text-success"/><b className="mt-1 block font-mono text-xs text-success">APPROVED</b></div></div><h2 className="mt-5 text-2xl font-semibold">Ready for Interview</h2><p className="mt-2 text-muted-foreground">Environment, media integrity, and sample recording evaluation complete.</p></div><section className="mt-10 border-t border-foreground/20">{verifications.map(([I,t,d]:any,i)=><article key={t} className="grid items-center gap-4 border-b border-foreground/15 bg-white p-5 md:grid-cols-[38px_1fr_90px]"><I className="text-brand"/><div><h3 className="font-semibold">{t}</h3><p className="mt-1 text-sm text-muted-foreground">{d}</p></div><Status status="PASS"/></article>)}</section><div className="mt-9 flex justify-center"><Button onClick={()=>navigate({to:"/interview/demo"})} size="lg" className={violetButton}>Start Mock Interview <ArrowRight/></Button></div></div></main>;
}

type Workspace="Conversation"|"Transcript"|"Notes"|"Whiteboard"|"Summary";
export function InterviewPage() {
  const navigate=useNavigate(); const [workspace,setWorkspace]=useState<Workspace>("Conversation"); const [drawer,setDrawer]=useState(true); const [echo,setEcho]=useState<EchoMode>("idle"); const [muted,setMuted]=useState(false); const [video,setVideo]=useState(true); const [paused,setPaused]=useState(false); const [messages,setMessages]=useState([{from:"assistant" as const,text:"Tell me about the highest-scale backend system you’ve owned."},{from:"user" as const,text:"I built a distributed order processing pipeline handling 20,000 events per second."},{from:"assistant" as const,text:"Good. How would you design that system to survive a full regional outage?"}]);
  function command(text:string){const q=text.toLowerCase();setMessages(m=>[...m,{from:"user",text}]);setEcho("thinking");window.setTimeout(()=>{let reply="I’m ready when you are.";if(q.includes("whiteboard")){setWorkspace("Whiteboard");setDrawer(true);reply="Opening the whiteboard."}else if(q.includes("transcript")){setWorkspace("Transcript");setDrawer(true);reply="Showing the live transcript."}else if(q.includes("notes")){setWorkspace("Notes");setDrawer(true);reply="Opening your notes."}else if(q.includes("repeat")){reply="Repeating the current question: How would you design a globally distributed URL shortening service?"}else if(q.includes("pause")){setPaused(true);reply="Interview paused."}setMessages(m=>[...m,{from:"assistant",text:reply}]);setEcho("speaking");window.setTimeout(()=>setEcho("idle"),1800)},900)}
  return <main className="h-screen overflow-hidden bg-[#120f16] text-white"><Header dark compact/><div className="flex h-[calc(100vh-56px)]">
    <section className="relative min-w-0 flex-1 overflow-hidden"><img src={alexImage} alt="Alex, AI technical interviewer" width={1280} height={720} className="absolute inset-0 size-full object-cover opacity-85"/><div className="absolute inset-0 bg-[linear-gradient(180deg,rgba(18,15,22,.7),transparent_25%,transparent_52%,rgba(18,15,22,.96))]"/>
      <div className="absolute inset-x-0 top-0 flex items-center justify-between px-5 py-4"><div><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-widest text-white/65"><span className="size-2 rounded-full bg-red-500"/> EchoSphere AI · Live</div><h2 className="mt-1 text-xl font-semibold">Alex <span className="text-sm font-normal text-white/50">· Technical Interviewer</span></h2></div><div className="flex gap-4 font-mono text-[10px] text-white/60"><span className="flex items-center gap-2"><Network className="size-3 text-success"/> Excellent</span><span className="flex items-center gap-2"><Radio className="size-3 text-red-400"/> REC</span><span>28:14</span></div></div>
      <div className="absolute left-5 top-24 hidden gap-1 md:flex">{["Verify ✓","Technical","Product","Behavioral","Confirm"].map((x,i)=><span key={x} className={cn("border px-3 py-2 font-mono text-[9px] uppercase",i===1?"border-highlight bg-highlight text-black":i===0?"border-white/25 text-white/45":"border-white/10 text-white/30")}>{x}</span>)}</div>
      <div className="absolute right-5 top-24 h-40 w-52 overflow-hidden border border-white/20 bg-black shadow-xl"><img src={candidateImage} alt="Arjun Sharma candidate video" width={640} height={640} className="size-full object-cover"/><span className="absolute bottom-2 left-2 bg-black/60 px-2 py-1 text-[10px]">Arjun Sharma</span></div>
      <div className="absolute bottom-0 left-0 right-0 px-5 pb-5 md:px-10"><div className="mx-auto max-w-4xl"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-highlight">System design · Follow-up · Hard · Technical depth</p><h1 className="mt-3 max-w-3xl text-2xl font-medium leading-tight md:text-4xl">How would you design a globally distributed URL shortening service?</h1><div className="mt-5 flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={()=>setMuted(!muted)} aria-label="Toggle microphone" className={cn("grid size-11 place-items-center rounded-full",muted?"bg-red-500":"bg-white text-black")}>{muted?<MicOff/>:<Mic/>}</button><button onClick={()=>setVideo(!video)} aria-label="Toggle camera" className="grid size-11 place-items-center rounded-full bg-white/10">{video?<Video/>:<VideoOff/>}</button><button className="grid size-11 place-items-center rounded-full bg-white/10"><MonitorUp/></button><button className="grid size-11 place-items-center rounded-full bg-white/10"><MoreHorizontal/></button></div><button onClick={()=>navigate({to:"/report"})} className="border border-red-400/60 bg-red-500/10 px-4 py-3 text-xs font-semibold text-red-300">End Interview</button></div></div></div>
      {paused&&<div className="absolute inset-0 z-20 grid place-items-center bg-black/65 backdrop-blur-sm"><div className="text-center"><CirclePause className="mx-auto size-12 text-highlight"/><h2 className="mt-3 text-3xl font-semibold">Interview paused</h2><Button onClick={()=>setPaused(false)} className="mt-5 rounded-none bg-highlight text-black hover:bg-white"><Play/> Resume interview</Button></div></div>}
      <div className="absolute bottom-6 left-1/2 z-30 -translate-x-1/2 translate-y-1/2 md:bottom-5"><EchoOrb mode={echo} onClick={()=>setEcho(echo==="idle"?"listening":"idle")}/><span className="mt-1 block text-center font-mono text-[9px] uppercase text-white/60">{echo==="idle"?"Hey Echo":echo==="listening"?"Listening…":echo==="thinking"?"Thinking…":"Speaking"}</span></div>
    </section>
    {drawer&&<aside className="absolute inset-y-14 right-0 z-30 flex w-full flex-col border-l border-white/10 bg-[#1b1720] shadow-2xl md:relative md:inset-y-0 md:w-[390px]"><div className="flex items-center justify-between border-b border-white/10 px-4"><div className="flex overflow-x-auto">{(["Conversation","Transcript","Notes","Whiteboard","Summary"] as Workspace[]).map(x=><button onClick={()=>setWorkspace(x)} key={x} className={cn("border-b-2 px-2.5 py-4 text-[10px] font-semibold",workspace===x?"border-highlight text-white":"border-transparent text-white/40")}>{x}</button>)}</div><button onClick={()=>setDrawer(false)}><X className="size-4"/></button></div><div className="min-h-0 flex-1 overflow-y-auto p-4">{workspace==="Conversation"&&<Conversation messages={messages}/>} {workspace==="Transcript"&&<Transcript/>} {workspace==="Notes"&&<textarea defaultValue="Ask about data consistency tradeoffs.&#10;&#10;Mention Kafka partition strategy." className="h-full w-full resize-none border border-white/15 bg-white/5 p-4 text-sm outline-none focus:border-brand"/>} {workspace==="Whiteboard"&&<Whiteboard/>} {workspace==="Summary"&&<Summary/>}</div>{workspace==="Conversation"&&<div className="border-t border-white/10 p-3"><PromptInput onSubmit={({text})=>text&&command(text)} className="border-white/15 bg-white/5"><PromptInputBody><PromptInputTextarea placeholder="Type or say ‘Hey Echo…’" className="text-white"/></PromptInputBody><PromptInputFooter><PromptInputTools><button onClick={()=>setEcho("listening")} type="button" className="p-2"><Mic className="size-4"/></button></PromptInputTools><PromptInputSubmit/></PromptInputFooter></PromptInput></div>}</aside>}
    {!drawer&&<button onClick={()=>setDrawer(true)} className="absolute right-4 top-20 z-30 flex items-center gap-2 border border-white/15 bg-[#211b27] px-3 py-2 text-xs"><MessageSquare className="size-4"/> Workspace</button>}
  </div></main>;
}
function Conversation({messages}:{messages:{from:"assistant"|"user";text:string}[]}) { return <div className="space-y-5">{messages.map((m,i)=><Message from={m.from} key={i}><p className="mb-1 font-mono text-[9px] uppercase tracking-widest text-white/35">{m.from==="assistant"?"Alex · AI Interviewer":"You"}</p><MessageContent className={cn("text-sm leading-6",m.from==="user"?"bg-brand px-3 py-2 text-white":"text-white/75")}><MessageResponse>{m.text}</MessageResponse></MessageContent></Message>)}</div> }
function Transcript(){return <div className="space-y-5">{[["00:19","Alex","Tell me about the highest-scale backend system you’ve owned."],["01:02","You","I built a distributed order processing pipeline handling 20,000 events per second."],["02:44","Alex","How did you reason about regional failure?"]].map(([t,n,x])=><div key={t} className="border-l border-white/15 pl-4"><span className="font-mono text-[9px] text-highlight">{t} · {n}</span><p className="mt-1 text-sm leading-6 text-white/70">{x}</p></div>)}</div>}
function Whiteboard(){return <div><p className="font-mono text-[9px] uppercase tracking-widest text-highlight">Architecture sketch</p><div className="relative mt-4 h-72 border border-white/15 bg-[linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] bg-[size:20px_20px]"><div className="absolute left-4 top-8 border border-info px-3 py-2 text-xs">Client</div><div className="absolute left-32 top-8 border border-highlight px-3 py-2 text-xs">API Gateway</div><div className="absolute bottom-12 left-28 border border-success px-3 py-2 text-xs">Cache</div><div className="absolute bottom-12 right-5 border border-brand px-3 py-2 text-xs">Database</div><svg className="absolute inset-0 size-full"><path d="M65 50 L128 50 M180 66 L165 180 M195 180 L285 180" stroke="rgba(255,255,255,.4)" fill="none" strokeDasharray="4 4"/></svg></div><div className="mt-4 space-y-2">{["Open thread · consistency model","Claim · cache-first reads","Competency · system design"].map(x=><p key={x} className="border border-white/10 p-3 text-xs text-white/60">{x}</p>)}</div></div>}
function Summary(){return <div><h3 className="text-xl font-semibold">Live observations</h3><div className="mt-5 space-y-3">{["Strong initial decomposition","Clear throughput assumptions","Needs deeper failure-mode analysis"].map((x,i)=><div key={x} className="flex gap-3 border-b border-white/10 pb-3"><span className="font-mono text-[10px] text-highlight">0{i+1}</span><p className="text-sm text-white/70">{x}</p></div>)}</div></div>}

export function ReportPage() {
  const navigate=useNavigate(); const panelScores=[["Alex","Technical Interviewer",84],["Maya","Product Manager",68],["Daniel","Hiring Manager",81]];
  return <main className="min-h-screen bg-[#17131c] text-white"><Header dark/><div className="mx-auto max-w-6xl px-5 py-12"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><Eyebrow dark>Evidence-backed assessment</Eyebrow><h1 className="text-5xl font-semibold tracking-[-.05em] md:text-7xl">Interview Report</h1><p className="mt-4 text-white/55">Arjun Sharma · Backend Engineer at Amazon · May 18, 2025 · 52 min</p></div><div className="flex gap-2"><Button variant="outline" className="rounded-none border-white/20 bg-transparent text-white"><Download/> Download Report</Button><Button onClick={()=>navigate({to:"/dashboard"})} className="rounded-none bg-highlight text-black hover:bg-white">Back to Dashboard</Button></div></div>
    <section className="mt-12 grid gap-px bg-white/10 lg:grid-cols-[260px_1fr_1fr]"><div className="bg-brand p-7"><p className="font-mono text-[10px] uppercase tracking-widest text-white/60">Overall score</p><p className="mt-5 text-8xl font-semibold tracking-tight">82</p><p className="mt-2 text-sm">Strong Hire</p><div className="mt-12 border-t border-white/25 pt-4"><span className="text-xs text-white/60">Confidence</span><b className="float-right">91%</b></div></div><div className="bg-[#211c27] p-7"><h2 className="flex items-center gap-2 font-semibold"><CheckCircle2 className="size-4 text-success"/> Key strengths</h2><ul className="mt-5 space-y-3 text-sm text-white/65">{["Strong debugging ability","Good backend fundamentals","Clear logical communication","Ownership and teamwork examples"].map(x=><li key={x} className="border-b border-white/10 pb-3">{x}</li>)}</ul></div><div className="bg-[#211c27] p-7"><h2 className="flex items-center gap-2 font-semibold"><Target className="size-4 text-highlight"/> Areas for improvement</h2><ul className="mt-5 space-y-3 text-sm text-white/65">{["Develop advanced technical depth","Connect implementation decisions to user impact","Quantify outcomes with clearer metrics"].map(x=><li key={x} className="border-b border-white/10 pb-3">{x}</li>)}</ul></div></section>
    <section className="mt-12"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-widest text-highlight">Seven dimensions</p><h2 className="mt-2 text-3xl font-semibold">Competency profile</h2></div><p className="text-xs text-white/45">Score / confidence / evidence</p></div><div className="mt-6 border-t border-white/15">{competencies.map(([n,v],i)=><article key={n} className="grid items-center gap-4 border-b border-white/10 py-5 md:grid-cols-[180px_1fr_70px_100px]"><div><h3 className="font-semibold">{n}</h3><p className="mt-1 text-[10px] text-white/35">Confidence {87-i}%</p></div><div><div className="h-2 bg-white/10"><div className={cn("h-full",v<70?"bg-highlight":"bg-brand")} style={{width:`${v}%`}}/></div><p className="mt-2 text-xs text-white/45">{v>80?"Demonstrated clear structure and relevant depth.":v>70?"Consistent evidence with room for more precision.":"Needs stronger links between decisions and user outcomes."}</p></div><strong className="text-2xl">{v}</strong><Button size="sm" variant="outline" className="rounded-none border-white/15 bg-transparent text-white">View Evidence</Button></article>)}</div></section>
    <section className="mt-12 grid gap-8 lg:grid-cols-2"><div><p className="font-mono text-[10px] uppercase tracking-widest text-highlight">Distinct perspectives</p><h2 className="mt-2 text-3xl font-semibold">Panel scores</h2><div className="mt-5 grid gap-3">{panelScores.map(([n,r,s]:any)=><div key={n} className="flex items-center gap-4 border border-white/10 bg-white/[.03] p-4"><span className="grid size-10 place-items-center bg-white/10">{n[0]}</span><div className="flex-1"><b>{n}</b><p className="text-xs text-white/40">{r}</p></div><strong className="text-2xl">{s}</strong></div>)}</div></div><div className="border border-highlight/40 bg-highlight/5 p-6"><div className="flex items-center gap-3"><Zap className="text-highlight"/><div><p className="font-mono text-[10px] uppercase tracking-widest text-highlight">Analytical signal</p><h2 className="mt-1 text-2xl font-semibold">Panel disagreement detected.</h2></div></div><p className="mt-5 text-sm leading-6 text-white/60">Alex rated technical depth highly, while Maya found weaker evidence connecting implementation choices to customer impact. This is not inconsistency—it reveals distinct assessment dimensions.</p><div className="mt-7 grid grid-cols-2 gap-3"><div className="border border-white/10 p-4"><span className="text-xs text-white/45">Technical view</span><b className="mt-2 block text-3xl">84</b></div><div className="border border-white/10 p-4"><span className="text-xs text-white/45">Product view</span><b className="mt-2 block text-3xl text-highlight">68</b></div></div></div></section>
    <section className="mt-12 border-t border-white/15 pt-9"><Eyebrow dark>Personalized roadmap</Eyebrow><h2 className="text-3xl font-semibold">Your improvement plan</h2><div className="mt-6 grid gap-px bg-white/10 md:grid-cols-4">{["Practice system-design tradeoffs.","Quantify project outcomes with metrics.","Connect technical decisions to customer impact.","Practice STAR-format behavioral responses."].map((x,i)=><div key={x} className="bg-[#211c27] p-5"><span className="font-mono text-xs text-highlight">0{i+1}</span><p className="mt-12 font-semibold leading-6">{x}</p><button className="mt-5 text-xs text-white/45">Start practice <ArrowRight className="ml-1 inline size-3"/></button></div>)}</div></section>
  </div><EchoAssistant dark hint="Ask Echo to explain any score."/></main>;
}