/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as AuthenticatedAnalysisRouteImport } from './routes/_authenticated/analysis'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedReportRouteImport } from './routes/_authenticated/report'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSystemCheckRouteImport } from './routes/_authenticated/system-check'
import { Route as AuthenticatedVideoTestRouteImport } from './routes/_authenticated/video-test'
import { Route as AuthenticatedInterviewThreadIdRouteImport } from './routes/_authenticated/interview.$threadId'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalysisRoute = AuthenticatedAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportRoute = AuthenticatedReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemCheckRoute =
  AuthenticatedSystemCheckRouteImport.update({
    id: '/system-check',
    path: '/system-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoTestRoute = AuthenticatedVideoTestRouteImport.update({
  id: '/video-test',
  path: '/video-test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInterviewThreadIdRoute =
  AuthenticatedInterviewThreadIdRouteImport.update({
    id: '/interview/$threadId',
    path: '/interview/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/report': typeof AuthenticatedReportRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/system-check': typeof AuthenticatedSystemCheckRoute
  '/video-test': typeof AuthenticatedVideoTestRoute
  '/interview/$threadId': typeof AuthenticatedInterviewThreadIdRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/analysis': typeof AuthenticatedAnalysisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/report': typeof AuthenticatedReportRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/system-check': typeof AuthenticatedSystemCheckRoute
  '/video-test': typeof AuthenticatedVideoTestRoute
  '/interview/$threadId': typeof AuthenticatedInterviewThreadIdRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/portal': typeof PortalRoute
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/report': typeof AuthenticatedReportRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/system-check': typeof AuthenticatedSystemCheckRoute
  '/_authenticated/video-test': typeof AuthenticatedVideoTestRoute
  '/_authenticated/interview/$threadId': typeof AuthenticatedInterviewThreadIdRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/portal'
    | '/analysis'
    | '/dashboard'
    | '/organization'
    | '/report'
    | '/roadmap'
    | '/setup'
    | '/system-check'
    | '/video-test'
    | '/interview/$threadId'
    | '/profile/edit'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/portal'
    | '/analysis'
    | '/dashboard'
    | '/organization'
    | '/report'
    | '/roadmap'
    | '/setup'
    | '/system-check'
    | '/video-test'
    | '/interview/$threadId'
    | '/profile/edit'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/portal'
    | '/_authenticated/analysis'
    | '/_authenticated/dashboard'
    | '/_authenticated/organization'
    | '/_authenticated/report'
    | '/_authenticated/roadmap'
    | '/_authenticated/setup'
    | '/_authenticated/system-check'
    | '/_authenticated/video-test'
    | '/_authenticated/interview/$threadId'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalRoute: typeof PortalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report': {
      id: '/_authenticated/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AuthenticatedReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-check': {
      id: '/_authenticated/system-check'
      path: '/system-check'
      fullPath: '/system-check'
      preLoaderRoute: typeof AuthenticatedSystemCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-test': {
      id: '/_authenticated/video-test'
      path: '/video-test'
      fullPath: '/video-test'
      preLoaderRoute: typeof AuthenticatedVideoTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/$threadId': {
      id: '/_authenticated/interview/$threadId'
      path: '/interview/$threadId'
      fullPath: '/interview/$threadId'
      preLoaderRoute: typeof AuthenticatedInterviewThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalysisRoute: typeof AuthenticatedAnalysisRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedReportRoute: typeof AuthenticatedReportRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSystemCheckRoute: typeof AuthenticatedSystemCheckRoute
  AuthenticatedVideoTestRoute: typeof AuthenticatedVideoTestRoute
  AuthenticatedInterviewThreadIdRoute: typeof AuthenticatedInterviewThreadIdRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalysisRoute: AuthenticatedAnalysisRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedReportRoute: AuthenticatedReportRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSystemCheckRoute: AuthenticatedSystemCheckRoute,
  AuthenticatedVideoTestRoute: AuthenticatedVideoTestRoute,
  AuthenticatedInterviewThreadIdRoute: AuthenticatedInterviewThreadIdRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalRoute: PortalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
