/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SystemCheckRouteImport } from './routes/system-check'
import { Route as VideoTestRouteImport } from './routes/video-test'
import { Route as InterviewThreadIdRouteImport } from './routes/interview.$threadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemCheckRoute = SystemCheckRouteImport.update({
  id: '/system-check',
  path: '/system-check',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoTestRoute = VideoTestRouteImport.update({
  id: '/video-test',
  path: '/video-test',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewThreadIdRoute = InterviewThreadIdRouteImport.update({
  id: '/interview/$threadId',
  path: '/interview/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/setup': typeof SetupRoute
  '/system-check': typeof SystemCheckRoute
  '/video-test': typeof VideoTestRoute
  '/interview/$threadId': typeof InterviewThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/setup': typeof SetupRoute
  '/system-check': typeof SystemCheckRoute
  '/video-test': typeof VideoTestRoute
  '/interview/$threadId': typeof InterviewThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/dashboard': typeof DashboardRoute
  '/portal': typeof PortalRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/setup': typeof SetupRoute
  '/system-check': typeof SystemCheckRoute
  '/video-test': typeof VideoTestRoute
  '/interview/$threadId': typeof InterviewThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/portal'
    | '/profile'
    | '/report'
    | '/setup'
    | '/system-check'
    | '/video-test'
    | '/interview/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/portal'
    | '/profile'
    | '/report'
    | '/setup'
    | '/system-check'
    | '/video-test'
    | '/interview/$threadId'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/dashboard'
    | '/portal'
    | '/profile'
    | '/report'
    | '/setup'
    | '/system-check'
    | '/video-test'
    | '/interview/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  DashboardRoute: typeof DashboardRoute
  PortalRoute: typeof PortalRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  SetupRoute: typeof SetupRoute
  SystemCheckRoute: typeof SystemCheckRoute
  VideoTestRoute: typeof VideoTestRoute
  InterviewThreadIdRoute: typeof InterviewThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-check': {
      id: '/system-check'
      path: '/system-check'
      fullPath: '/system-check'
      preLoaderRoute: typeof SystemCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-test': {
      id: '/video-test'
      path: '/video-test'
      fullPath: '/video-test'
      preLoaderRoute: typeof VideoTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$threadId': {
      id: '/interview/$threadId'
      path: '/interview/$threadId'
      fullPath: '/interview/$threadId'
      preLoaderRoute: typeof InterviewThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  DashboardRoute: DashboardRoute,
  PortalRoute: PortalRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  SetupRoute: SetupRoute,
  SystemCheckRoute: SystemCheckRoute,
  VideoTestRoute: VideoTestRoute,
  InterviewThreadIdRoute: InterviewThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
